
# This config file is meant for settings that affect your whole blog, values which you are expected to set up once and rarely edit after that. If you find yourself editing this file very often, consider using Jekyll's data files feature for the data you need to update frequently.
# For technical reasons, this file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'. If you change this file, please restart the server process.
# If you need help with YAML syntax, here are some quick references for you:
#  https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
#  https://learnxinyminutes.com/docs/yaml/
# Site settings: These are used to personalize your new site. If you look in the HTML files, you will see them accessed via {{ site.title }}, {{ site.email }}, and so on. You can create any custom variable you would like, and they will be accessible in the templates via {{ site.myvariable }}.

title: Joseph's IT thoughts
author:
  name: Joseph Harriott
  email: trohib_at_gmail_com
description: >- # this means to ignore newlines until "baseurl:"
  Self-taught geekology.
  I love Arch Linux, Bash, Vim, LaTeX, Python, FFmpeg, ImageMagick and in general wrangling stuff from the command-line.
  I also keep up with PowerShell on my Windows Pro laptop, and I use Markdown, Dokuwiki, and Pandoc daily.
baseurl: "" # the subpath of your site, e.g. /blog
url: harriott.github.io
twitter_username: joharrio
github_username:  harriott

# show_excerpts: true  # before calling minima

# Build settings
# --------------
plugins:
  # - jekyll-feed
  - jekyll-remote-theme
remote_theme: jekyll/minima
# theme: minima  # uses the standard gem

# Exclude from processing.
# ------------------------
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

minima:
  skin: dark  # having no effect

