
# $JHw/IT-Jekyll-harriott/_config.yml - if changed,  bundle exec jekyll s
# see  $GHrUse/CP/Jekyll/jekyll-jekyll/lib/site_template/_config.yml

#=> 0 site description
title: Joseph's IT thoughts
author:
  name: Joseph Harriott
  email: trohib_at_gmail_com
description: >-  # (= ignore newlines until next descriptor)
  geekology
baseurl: ""  # the subpath of your site, e.g. /blog
url: harriott.github.io
twitter_username: joharrio
github_username: harriott

#=> 1 build settings
defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

include: [_pages]

plugins:
  # - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

#=> 2 theme
logo: /assets/c6o-Skype2Frame40-square.png
# show_excerpts: true  # before calling minima

#==> minima
# gem, infrequently updated
# theme: minima

# remote (= latest) version
minima:
  social_links:  # in footer
    - { platform: stackoverflow, user_url: "https://stackoverflow.com/users/2595845/joharr" }
    - { platform: github, user_url: "https://github.com/harriott" }
    - { platform: twitter, user_url: "https://twitter.com/joharrio" }
  skin: dark
remote_theme: jekyll/minima

